#!/usr/bin/env python3
"""Generate amulet_plan_b_fixup.yaml — fixup shards for two Plan B failures.

Plan B failures discovered after merging results:

1. Wisconsin × {GPF, GPF-plus, Gprompt, All-in-one} all FAILED due to
   WebKB multi-split train_mask bug (now fixed in induced_graph.py).
   4 prompts × 5 pretrains × 3 shots × 1 dataset = 60 cells to rerun.

2. MultiGprompt × * FAILED for all 4 datasets due to return_pre_train_type
   missing 'MultiGprompt' in valid_names (now fixed in task.py).
   1 prompt × 1 pretrain × 4 datasets × 3 shots = 12 cells to rerun.
   Plus: MultiGprompt as a pretrain is missing for all other prompts ×
   4 datasets × 3 shots, but per Plan A those combos were also missing —
   need a deeper fix in bench_full_grid.sh ckpt path resolution. Skip for now.

Total fixup: ~72 cells across 8 shards.

Sharding (8 shards = 4 Wisconsin re-runs + 4 MultiGprompt re-runs):

- gpf-wisconsin, gpf-plus-wisconsin, gprompt-wisconsin, all-in-one-wisconsin
  — each runs all 3 shots × 5 pretrains
- multigprompt-cora, multigprompt-wisconsin, multigprompt-mutag, multigprompt-proteins
  — each runs all 3 shots with MultiGprompt pretrain + MultiGprompt prompt
"""

from __future__ import annotations

import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "amulet_plan_b_fixup.yaml"

UAI = (
    "/subscriptions/b6dc87f3-c479-49c8-8cb5-7896da3ff895"
    "/resourceGroups/AMLStudio/providers/Microsoft.ManagedIdentity"
    "/userAssignedIdentities/rankfun_aml"
)

ALL_PRETRAINS = "None DGI GraphCL GraphMAE Edgepred_Gprompt MultiGprompt"
NODE_PRETRAIN_METHODS = "DGI GraphCL GraphMAE Edgepred_Gprompt MultiGprompt"
GRAPH_PRETRAIN_METHODS = NODE_PRETRAIN_METHODS

SHOTS = "1 3 5"

# Each row: (shard_name, prompts, datasets, pretrain_methods,
#            bench_pretrains, bench_shots, extra_flags)
SHARDS: list[tuple[str, str, str, str, str, str, str]] = [
    # ===== Wisconsin × dual-task prompts that failed (WebKB train_mask bug) =====
    ("gpf-wisconsin-fix", "GPF", "Wisconsin", NODE_PRETRAIN_METHODS, ALL_PRETRAINS, SHOTS, ""),
    (
        "gpf-plus-wisconsin-fix",
        "GPF-plus",
        "Wisconsin",
        NODE_PRETRAIN_METHODS,
        ALL_PRETRAINS,
        SHOTS,
        "",
    ),
    (
        "gprompt-wisconsin-fix",
        "Gprompt",
        "Wisconsin",
        NODE_PRETRAIN_METHODS,
        ALL_PRETRAINS,
        SHOTS,
        "",
    ),
    (
        "all-in-one-wisconsin-fix",
        "All-in-one",
        "Wisconsin",
        NODE_PRETRAIN_METHODS,
        ALL_PRETRAINS,
        SHOTS,
        "",
    ),
    # ===== MultiGprompt × all 4 datasets (return_pre_train_type bug) =====
    ("multigprompt-cora", "MultiGprompt", "Cora", "MultiGprompt", "MultiGprompt", SHOTS, ""),
    (
        "multigprompt-wisconsin",
        "MultiGprompt",
        "Wisconsin",
        "MultiGprompt",
        "MultiGprompt",
        SHOTS,
        "",
    ),
    ("multigprompt-mutag", "MultiGprompt", "MUTAG", "MultiGprompt", "MultiGprompt", SHOTS, ""),
    (
        "multigprompt-proteins",
        "MultiGprompt",
        "PROTEINS",
        "MultiGprompt",
        "MultiGprompt",
        SHOTS,
        "",
    ),
]


assert len(SHARDS) == 8, f"expected 8 shards, got {len(SHARDS)}"


def render_job(
    shard_name: str,
    prompts: str,
    datasets: str,
    pretrain_methods: str,
    bench_pretrains: str,
    bench_shots: str,
    extra: str,
) -> str:
    block = f"""\
  - name: {shard_name}
    sku: 80G1-A100
    sla_tier: Standard
    submit_args:
      env:
        AMLT_DOCKERFILE_TEMPLATE: DEFAULT
        _AZUREML_SINGULARITY_JOB_UAI: {UAI}
    command:
      - set -euo pipefail
      - export SHARD_NAME='{shard_name}'
      - export PRETRAIN_METHODS='{pretrain_methods}'
      - export PRETRAIN_DATASETS='{datasets}'
      - export BENCH_PROMPTS='{prompts}'
      - export BENCH_DATASETS='{datasets}'
      - export BENCH_PRETRAINS='{bench_pretrains}'
      - export BENCH_SHOTS='{bench_shots}'
      - export BENCH_EXTRA_FLAGS='{extra}'
      - bash $$AMLT_CODE_DIR/scripts/amlt_shard_run.sh
"""
    return block


def main() -> None:
    header = textwrap.dedent("""\
        # Auto-generated by scripts/gen_amulet_plan_b_fixup.py — DO NOT EDIT BY HAND.
        # Fixup for two Plan B failures:
        #   1. Wisconsin × {GPF, GPF-plus, Gprompt, All-in-one} — WebKB train_mask
        #      bug now fixed in prompt_graph/data/induced_graph.py
        #   2. MultiGprompt prompt on all 4 datasets — return_pre_train_type bug
        #      now fixed in prompt_graph/tasker/task.py
        #
        # Total: 8 single-A100 shards × ~10-20min each.

        description: ProG Plan B fixup — Wisconsin GPF/Gprompt/All-in-one + MultiGprompt prompt × 4 datasets

        environment:
          image: amlt-sing/acpt-torch2.8.x-py3.10-cuda12.6-ubuntu22.04
          setup:
            - python --version
            - nvidia-smi || true

        code:
          local_dir: $CONFIG_DIR

        target:
          service: sing
          name: Feeds
          workspace_name: CS-NewsAndFeeds-Singularity@rg-cs-newsandfeeds-singularity

        jobs:
        """)
    body = "".join(render_job(*s) for s in SHARDS)
    OUT_PATH.write_text(header + body, encoding="utf-8")
    print(f"Wrote {OUT_PATH} with {len(SHARDS)} shards")
    for s in SHARDS:
        print(f"  - {s[0]:<28s} prompts=[{s[1]}] datasets=[{s[2]}] shots=[{s[5]}]")


if __name__ == "__main__":
    main()
